name = 'anymore-free-mail'
main = "src/server.js"
compatibility_date = "2026-03-18"

# D1 数据库绑定
[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "maill_free_db"
database_id = "3e5777a4-0ddf-1f69-74f3-e82ad1a2ce09"

# R2 存储桶绑定
[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml"

# 静态资源
[assets]
directory = "public"
binding = "ASSETS"

# 敏感配置建议不要放在这里
# FORWARD_RULES 请使用 wrangler secret put 或 .dev.vars 处理